apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-ns
    pod-template-hash: 74798bd985
  name: my-dep-74798bd985-bt97k
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-ns
    pod-template-hash: 74798bd985
  type: NodePort
status:
  loadBalancer: {}
