# Depricated method
apiVersion: v1
kind: ReplicationController # view with kubectl get replicationcontrollers 
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template: 
    metadata: # metadata and spec copied from required-fields yaml file (line 10 - 18)
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3