apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: myapp
    type: frontend
  name: myapp-rc

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
